import type { Recipe } from '../../../scripts/recipe-types'

export const recipe: Recipe = {
  domain: 'mozilla.org/nss',
  name: 'nss',
  programs: [
    'addbuiltin',
    'certutil',
    'crmftest',
    'ecperf',
    'listsuites',
    'multinit',
    'ocspresp',
    'p7verify',
    'pk12util',
    'remtest',
    'secmodtest',
    'ssltap',
    'vfychain',
    'atob',
    'chktest',
    'dbtest',
    'encodeinttest',
    'nonspr10',
    'oidcalc',
    'pk11ectest',
    'pk1sign',
    'rsaperf',
    'selfserv',
    'strsclnt',
    'vfyserv',
    'baddbdir',
    'cmsutil',
    'derdump',
    'fbectest',
    'makepqg',
    'nss-config',
    'p7content',
    'pk11gcmtest',
    'pkix-errcodes',
    'rsapoptst',
    'shlibsign',
    'symkeyutil',
    'bltest',
    'conflict',
    'dertimetest',
    'fipstest',
    'mangle',
    'nss-policy-check',
    'p7env',
    'pk11importtest',
    'pp',
    'sdbthreadtst',
    'signtool',
    'tstclnt',
    'btoa',
    'crlutil',
    'digest',
    'httpserv',
    'modutil',
    'ocspclnt',
    'p7sign',
    'pk11mode',
    'pwdecrypt',
    'sdrtest',
    'signver',
    'validation',
  ],
  dependencies: {
    'mozilla.org/nspr': '*',
    'sqlite.org': '*',
    'zlib.net': '*',
  },
  buildDependencies: {
    linux: {
      'gnu.org/gcc': '*',
      'gnu.org/make': '*',
    },
    'darwin/aarch64': {
      'llvm.org': '*',
    },
  },
  distributable: {
    url: 'https://ftp.mozilla.org/pub/security/nss/releases/NSS_{{version.major}}_{{version.minor}}_RTM/src/nss-{{version.marketing}}.tar.gz',
    stripComponents: 1,
  },
  build: {
    script: [
      {
        run: "sed -i 's|-install_name @executable_path|-install_name {{prefix}}/lib|g' coreconf/Darwin.mk\nsed -i 's|@executable_path|{{prefix}}/lib|g' lib/freebl/config.mk\nmake all $ARGS",
        'working-directory': 'nss',
      },
      {
        run: 'mkdir -p bin lib/pkgconfig include/dbm include/nss\ncat <<< "$PC_FILE" > lib/pkgconfig/nss.pc',
        'working-directory': '{{prefix}}',
      },
      'cat <<< "$CONFIG_FILE" > ./dist/nss-config',
      'install ./dist/nss-config {{prefix}}/bin/',
      'install ./dist/$(uname)*/bin/* {{prefix}}/bin/',
      'install ./dist/$(uname)*/lib/* {{prefix}}/lib/',
      'install ./dist/public/dbm/* {{prefix}}/include/dbm/',
      'install ./dist/public/nss/* {{prefix}}/include/nss/',
    ],
    env: {
      linux: {
        CC: '{{deps.gnu.org/gcc.prefix}}/bin/gcc',
      },
      'darwin/aarch64': {
        CC: '{{deps.llvm.org.prefix}}/bin/clang',
      },
      'darwin/x86-64': {
        CPU_ARCH: 'x86_64',
      },
      ARGS: [
        'BUILD_OPT=1',
        'NSS_ALLOW_SSLKEYLOGFILE=1',
        'NSS_DISABLE_GTESTS=1',
        'NSS_USE_SYSTEM_SQLITE=1',
        'NSPR_INCLUDE_DIR={{deps.mozilla.org/nspr.prefix}}/include/nspr',
        'NSPR_LIB_DIR={{deps.mozilla.org/nspr.prefix}}/lib',
        'USE_64=1',
      ],
      CONFIG_FILE: '#!/bin/sh\nfor opt; do :; done\ncase "\\$opt" in\n  --version) opt="--modversion";;\n  --cflags|--libs) ;;\n  *) exit 1;;\nesac\npkg-config "\\$opt" nss\n',
      PC_FILE: 'prefix=\\${pcfiledir}/../..\nexec_prefix=\\${prefix}\nlibdir=\\${exec_prefix}/lib\nincludedir=\\${prefix}/include/nss\n\nName: NSS\nDescription: Mozilla Network Security Services\nVersion: {{version}}\nRequires: nspr >= 4.12\nLibs: -L\\${libdir} -lnss3 -lnssutil3 -lsmime3 -lssl3\nCflags: -I\\${includedir}\n',
    },
  },
  test: {
    script: [
      'pkg-config --modversion nss | grep {{version}}',
      'certutil -N -d ./ -f passwd',
      'certutil -L -d ./ | grep "Certificate Nickname"',
    ],
  },
}
