import type { Recipe } from '../../scripts/recipe-types'

export const recipe: Recipe = {
  domain: 'ffmpeg.org',
  name: 'ffmpeg',
  description: 'Play, record, convert, and stream audio and video',
  homepage: 'https://ffmpeg.org/',
  github: 'https://github.com/FFmpeg/FFmpeg',
  programs: ['ffmpeg', 'ffplay', 'ffprobe'],
  versionSource: {
    type: 'github-tags',
    repo: 'FFmpeg/FFmpeg',
    tagPattern: /^n(\d+(?:\.\d+){0,3})$/,
  },
  distributable: {
    url: 'https://ffmpeg.org/releases/ffmpeg-{{version.raw}}.tar.gz',
    stripComponents: 1,
  },
  dependencies: {
    'lame.sourceforge.io': '>=3.98.3',
    'libsdl.org': '^2',
    'freetype.org': '^2',
    'harfbuzz.org': '^8',
    'videolan.org/x264': '^0.164',
    'videolan.org/x265': '^3',
    'webmproject.org/libvpx': '~1.14',
    'opus-codec.org': '^1',
    'google.com/webp': '^1',
  },
  buildDependencies: {
    'x86-64': {
      'nasm.us': '2',
    },
  },

  build: {
    script: [
      '# --enable-libharfbuzz is not available in all versions',
      'if grep -q -- --enable-libharfbuzz configure; then',
      '  ARGS="$ARGS --enable-libharfbuzz"',
      'fi',
      '',
      '# ffmpeg configure does not honor LIBRARY_PATH/CPATH for its compile/link',
      '# probes. lame ships NO pkg-config .pc file, so --enable-libmp3lame fails',
      '# with the "libmp3lame >= 3.98.3 not found" error unless the lame',
      '# include/lib dirs are passed explicitly. libvpx is found via pkg-config but',
      '# its decoder symbol probe (vpx_codec_dec_init_ver) fails to LINK ("libvpx',
      '# enabled but no supported decoders found") without an explicit -L. Feed every',
      '# dep prefix into ffmpeg via --extra-cflags / --extra-ldflags so all',
      '# detection probes resolve regardless of pkg-config availability.',
      '#',
      '# x264/x265/vpx/opus/webp are detected with ffmpeg configure\'s',
      '# require_pkg_config (a HARD pkg-config requirement) — e.g. x265 via',
      '# "require_pkg_config libx265 x265 x265.h x265_api_get". If a codec dep\'s',
      '# .pc dir is not already on PKG_CONFIG_PATH, configure aborts with',
      '# "ERROR: x265 not found using pkg-config". So also prepend every dep\'s',
      '# lib/pkgconfig (and share/pkgconfig) to PKG_CONFIG_PATH below.',
      'for _dep in \\',
      '  {{deps.lame.sourceforge.io.prefix}} \\',
      '  {{deps.libsdl.org.prefix}} \\',
      '  {{deps.freetype.org.prefix}} \\',
      '  {{deps.harfbuzz.org.prefix}} \\',
      '  {{deps.videolan.org/x264.prefix}} \\',
      '  {{deps.videolan.org/x265.prefix}} \\',
      '  {{deps.webmproject.org/libvpx.prefix}} \\',
      '  {{deps.opus-codec.org.prefix}} \\',
      '  {{deps.google.com/webp.prefix}}; do',
      '  if [ -d "$_dep/include" ]; then ARGS="$ARGS --extra-cflags=-I$_dep/include"; fi',
      '  if [ -d "$_dep/lib" ]; then ARGS="$ARGS --extra-ldflags=-L$_dep/lib"; fi',
      '  for _pc in "$_dep/lib/pkgconfig" "$_dep/share/pkgconfig"; do',
      '    if [ -d "$_pc" ]; then PKG_CONFIG_PATH="$_pc:${PKG_CONFIG_PATH:-}"; fi',
      '  done',
      'done',
      'export PKG_CONFIG_PATH',
      '',
      './configure $ARGS',
      'make --jobs {{hw.concurrency}}',
      'make install',
    ],
    env: {
      'ARGS': [
        '--prefix={{prefix}}',
        '--enable-libfreetype',
        '--enable-libmp3lame',
        '--enable-shared',
        '--enable-libx264',
        '--enable-gpl', // required for x264
        '--enable-libx265',
        '--enable-libvpx',
        '--enable-libopus',
        '--enable-libwebp',
      ],
      'CFLAGS': ['-Wno-incompatible-function-pointer-types'],
    },
  },
}
