import type { Recipe } from '../../scripts/recipe-types'

export const recipe: Recipe = {
  domain: 'xpra.org',
  name: 'xpra',
  description: 'Persistent remote applications for X11; screen sharing for X11, MacOS and MSWindows.',
  homepage: 'https://xpra.org/',
  github: 'https://github.com/Xpra-org/xpra',
  programs: ['xpra'],
  platforms: ['linux'],
  versionSource: {
    type: 'github-releases',
    repo: 'Xpra-org/xpra',
  },
  distributable: {
    url: 'https://github.com/Xpra-org/xpra/archive/refs/tags/xpra {{version}}.tar.gz',
    stripComponents: 1,
  },
  dependencies: {
    'pkgx.sh': '>=1',
    'python.org': '~3.11',
    'cython.org': '*',
    'tukaani.org/xz': '*',
    'cairographics.org': '*',
    'cairographics.org/pycairo': '1.26.1',
    'freedesktop.org/pkg-config': '~0.29',
    'gnome.org/PyGObject': '*',
    'gnome.org/glib': '*',
    'x.org/x11': '*',
    'x.org/protocol': '*',
    'x.org/exts': '*',
    'x.org/xkbfile': '*',
    'x.org/xdamage': '*',
    'x.org/xrandr': '*',
    'x.org/xcomposite': '*',
    'x.org/xtst': '*',
    'x.org/libxres': '*',
    'x.org/xfixes': '*',
    'x.org/xcursor': '*',
    'videolan.org/x264': '*',
    'webmproject.org/libvpx': '*',
    'github.com/AOMediaCodec/libavif': '*',
    'github.com/Cyan4973/xxHash': '*',
    'gtk.org/gtk3': '*',
    'gnome.org/gobject-introspection': '*',
    'harfbuzz.org': '*',
    'gnome.org/gdk-pixbuf': '*',
    'gnome.org/atk': '*',
    'gnome.org/pango': '*',
  },

  build: {
    script: [
      'bkpyvenv stage {{prefix}} {{version}}',
      '${{prefix}}/venv/bin/pip install cython',
      '${{prefix}}/venv/bin/pip install . --no-build-isolation',
      'bkpyvenv seal {{prefix}} xpra',
    ],
  },
}
