import fs from 'node:fs'
import path from 'node:path'

export interface GenerateOptions {
  /** Directory to write the Dockerfile + .freezer into. */
  outDir: string
  /** Base image (default: oven/bun:1.3.14-alpine). */
  baseImage?: string
  /** Working directory inside the image (default: /app). */
  workdir?: string
  /** Dependency install command run at build. Production-only unless a build command needs dev dependencies. */
  installCommand?: string
  /** Optional build command (e.g. `bun run build`). */
  buildCommand?: string
  /** Start command as an exec array (default: bun start). */
  startCommand?: string[]
  /** Port the app listens on (default: 3000). */
  port?: number
  /** Environment defaults baked into the image. */
  env?: Record<string, string>
  /** Filename for the Dockerfile (default: Dockerfile). */
  dockerfileName?: string
  /** Overwrite existing files (default: false → skip if present). */
  force?: boolean
}

export interface GenerateResult {
  dockerfilePath: string
  freezerPath: string
  wroteDockerfile: boolean
  wroteFreezer: boolean
}

const DEFAULT_FREEZER = `# .freezer — pantry's home-themed .dockerignore.
# Anything matched here is kept OUT of the build context (and the image).
# Dependencies are reinstalled inside the image, so never ship them.
node_modules
**/node_modules
pantry
**/pantry

# VCS / CI / local noise
.git
.github
.cache
**/.cache
tmp
temp
**/*.log
.DS_Store

# Local-only env overlays — runtime config is provided at run time
.env.local
.env.*.local

# Build artifacts the image rebuilds or doesn't need
.pantry
coverage
.ts-cloud
`

/** Render a production Dockerfile for a Bun/Stacks-style app. */
export function renderDockerfile(opts: GenerateOptions): string {
  const base = opts.baseImage ?? 'oven/bun:1.3.14-alpine'
  const workdir = opts.workdir ?? '/app'
  const install = opts.installCommand ?? (opts.buildCommand
    ? 'bun install --frozen-lockfile'
    : 'bun install --frozen-lockfile --production')
  const port = opts.port ?? 3000
  const start = opts.startCommand ?? ['bun', 'start']
  const env = { APP_ENV: 'production', NODE_ENV: 'production', PORT: String(port), ...(opts.env ?? {}) }

  const lines: string[] = []
  lines.push('# Generated by `pantry container:generate` — native, depless container support.')
  lines.push('# Build with: pantry build -t <name> .   (no Docker daemon required)')
  lines.push(`FROM ${base} AS base`)
  lines.push(`WORKDIR ${workdir}`)
  lines.push('')
  lines.push('# Bring in the source (filtered by .freezer) and install deps in-image so')
  lines.push('# the build context / release stays small.')
  lines.push('COPY --chown=bun:bun . .')
  lines.push(`RUN ${install}`)
  if (opts.buildCommand) {
    lines.push(`RUN ${opts.buildCommand}`)
    if (!opts.installCommand)
      lines.push('RUN bun install --frozen-lockfile --production')
  }
  lines.push('')
  lines.push('# Source and runtime dependencies are owned by the non-root runtime user.')
  lines.push('USER bun')
  lines.push('')
  for (const [k, v] of Object.entries(env))
    lines.push(`ENV ${k}=${v}`)
  lines.push('')
  lines.push(`EXPOSE ${port}/tcp`)
  lines.push(`CMD ${JSON.stringify(start)}`)
  lines.push('')
  return lines.join('\n')
}

/**
 * Generate a Dockerfile + `.freezer` into `outDir` (e.g. `storage/framework`),
 * where tools like ts-cloud / CDK can pick them up.
 */
export function generateContainerFiles(opts: GenerateOptions): GenerateResult {
  fs.mkdirSync(opts.outDir, { recursive: true })
  const dockerfilePath = path.join(opts.outDir, opts.dockerfileName ?? 'Dockerfile')
  const freezerPath = path.join(opts.outDir, '.freezer')

  let wroteDockerfile = false
  let wroteFreezer = false

  if (opts.force || !fs.existsSync(dockerfilePath)) {
    fs.writeFileSync(dockerfilePath, renderDockerfile(opts))
    wroteDockerfile = true
  }
  if (opts.force || !fs.existsSync(freezerPath)) {
    fs.writeFileSync(freezerPath, DEFAULT_FREEZER)
    wroteFreezer = true
  }

  return { dockerfilePath, freezerPath, wroteDockerfile, wroteFreezer }
}
