import type { Recipe } from '../../../scripts/recipe-types'

export const recipe: Recipe = {
  domain: 'gnu.org/groff',
  name: 'groff',
  programs: [
    'addftinfo',
    'afmtodit',
    'chem',
    'eqn',
    'eqn2graph',
    'gdiffmk',
    'glilypond',
    'gperl',
    'gpinyin',
    'grap2graph',
    'grn',
    'grodvi',
    'groff',
    'grog',
    'grolbp',
    'grolj4',
    'gropdf',
    'grops',
    'grotty',
    'hpftodit',
    'indxbib',
    'lkbib',
    'lookbib',
    'mmroff',
    'neqn',
    'nroff',
    'pdfmom',
    'pfbtops',
    'pic',
    'pic2graph',
    'post-grohtml',
    'preconv',
    'pre-grohtml',
    'refer',
    'soelim',
    'tbl',
    'tfmtodit',
    'troff',
  ],
  dependencies: {
    'ghostscript.com': '*',
    'netpbm.sourceforge.net': '*',
    'github.com/rrthomas/psutils': '*',
    'freedesktop.org/uchardet': '*',
    'perl.org': '*',
    linux: {
      'gnome.org/glib': '*',
      'gnu.org/gcc/libstdcxx': '14',
    },
  },
  buildDependencies: {
    linux: {
      'gnu.org/gcc': '14',
    },
    'gnu.org/make': '*',
    'freedesktop.org/pkg-config': '*',
    'gnu.org/bison': '*',
    'gnu.org/texinfo': '*',
  },
  distributable: {
    url: 'https://ftp.gnu.org/gnu/groff/groff-{{version}}.tar.gz',
    stripComponents: 1,
  },
  build: {
    script: [
      './configure $ARGS',
      'make --jobs {{hw.concurrency}}',
      'make --jobs {{hw.concurrency}} install',
      {
        run: "sed -i \"1s|.*|#!/usr/bin/env perl|g\" afmtodit grog gropdf mmroff pdfmom\nsed -i \"s|$PKGX_DIR|\\$ENV{'PKGX_DIR'}|g\" afmtodit chem glilypond gperl gropdf\nsed -i \"s|$PKGX_DIR|\\$PKGX_DIR|g\" neqn nroff\nsed -i \"s|@g@||g\" neqn",
        'working-directory': '{{prefix}}/bin',
      },
    ],
    env: {
      darwin: {
        PERL: '${{deps.perl.org.prefix}}/bin/perl',
      },
      ARGS: [
        '--prefix={{prefix}}',
        '--without-x',
        '--with-uchardet',
      ],
    },
  },
  test: {
    script: [
      'groff --version | grep {{version}}',
      'grog --version | grep {{version}}',
      'neqn --version | grep {{version}}',
      'groff -Tps test.ms > test.ps',
      'cat test.ps | grep {{version}}',
    ],
  },
}
