import type { Recipe } from '../../../../scripts/recipe-types'

export const recipe: Recipe = {
  domain: 'github.com/mas-cli/mas',
  name: 'mas',
  programs: [
    'mas',
  ],
  platforms: ['darwin/aarch64', 'darwin/x86-64'],
  versionSource: {
    type: 'github-releases',
    repo: 'mas-cli/mas',
    tagPattern: /^v(.+)$/,
  },
  distributable: null,
  build: {
    script: [
      'case {{hw.arch}} in',
      '  aarch64) ARCH=arm64 ;;',
      '  x86-64) ARCH=x86_64 ;;',
      '  *) echo "unsupported arch {{hw.arch}}" >&2; exit 42 ;;',
      'esac',
      'PKG=mas-{{version}}-$ARCH.pkg',
      'curl --fail --location --retry 3 --retry-delay 2 --connect-timeout 15 --max-time 300 -o "$PKG" "https://github.com/mas-cli/mas/releases/download/v{{version}}/$PKG"',
      "/usr/bin/python3 <<'PY'",
      'from pathlib import Path',
      'import struct',
      'import zlib',
      'import xml.etree.ElementTree as ET',
      '',
      'pkg = next(Path(".").glob("mas-*.pkg"))',
      'data = pkg.read_bytes()',
      'magic, header_size, _version, toc_clen, _toc_ulen, _checksum = struct.unpack(">IHHQQI", data[:28])',
      'if magic != 0x78617221:',
      '    raise SystemExit(f"{pkg} is not a XAR package")',
      'toc = zlib.decompress(data[header_size:header_size + toc_clen])',
      'heap_start = header_size + toc_clen',
      'root = ET.fromstring(toc)',
      '',
      'def walk(node, parts):',
      '    name = node.findtext("name")',
      '    current = parts + ([name] if name else [])',
      '    if "/".join(current) == "mas.pkg/Payload":',
      '        payload = node.find("data")',
      '        offset = int(payload.findtext("offset"))',
      '        length = int(payload.findtext("length"))',
      '        Path("Payload").write_bytes(data[heap_start + offset:heap_start + offset + length])',
      '        return True',
      '    return any(walk(child, current) for child in node.findall("file"))',
      '',
      'if not any(walk(child, []) for child in root.find("toc").findall("file")):',
      '    raise SystemExit("mas.pkg/Payload not found")',
      'PY',
      'mkdir pkg-root',
      'gzip -dc Payload | (cd pkg-root && cpio -id)',
      'mkdir -p {{prefix}}',
      'cp -R pkg-root/usr/local/opt/mas/. {{prefix}}/',
    ],
    skip: ['verify-foreign-artifact'],
  },
  test: {
    script: [
      'test "$(mas --version)" = "{{version}}"',
      'test -x {{prefix}}/libexec/bin/mas',
    ],
  },
}
