//! Developer/debugging commands

const std = @import("std");
const io_helper = @import("../../io_helper.zig");
const lib = @import("../../lib.zig");
const common = @import("common.zig");
const style = @import("../style.zig");

const CommandResult = common.CommandResult;
const string = lib.string;

// Note: the live `dev:shellcode` integration is generated by
// `src/shell/generator.zig` from `src/shell/templates/shell_integration.sh`
// (wired via `shellCodeCommand`). A second, divergent shellcode generator used
// to live here; it was never routed by the CLI and has been removed to keep a
// single source of truth for the shell hook.

/// Dev: MD5 command - compute MD5 hash of a file or stdin
pub fn devMd5Command(allocator: std.mem.Allocator, path: []const u8) !CommandResult {
    const is_stdin = std.mem.eql(u8, path, "/dev/stdin");

    var hasher = std.crypto.hash.Md5.init(.{});

    if (is_stdin) {
        // Read from stdin (Zig 0.15 API)
        const stdin_file = std.io.getStdIn();
        var buf: [4096]u8 = undefined;
        while (true) {
            const bytes_read = try stdin_file.read(&buf);
            if (bytes_read == 0) break;
            hasher.update(buf[0..bytes_read]);
        }
    } else {
        // Read from file
        const file = io_helper.cwd().openFile(io_helper.io, path, .{}) catch |err| {
            const msg = try std.fmt.allocPrint(
                allocator,
                "Error: Failed to open file {s}: {}",
                .{ path, err },
            );
            return .{
                .exit_code = 1,
                .message = msg,
            };
        };
        defer file.close(io_helper.io);

        var buf: [4096]u8 = undefined;
        while (true) {
            const bytes_read = try file.read(&buf);
            if (bytes_read == 0) break;
            hasher.update(buf[0..bytes_read]);
        }
    }

    var digest: [16]u8 = undefined;
    hasher.final(&digest);

    // Convert to hex string
    const hex = try string.hashToHex(digest, allocator);
    defer allocator.free(hex);

    style.print("{s}\n", .{hex});

    return .{ .exit_code = 0 };
}

/// Dev: find-project-root command - find project root from a directory
pub fn devFindProjectRootCommand(allocator: std.mem.Allocator, start_dir: []const u8) !CommandResult {
    const detector = @import("../../deps/detector.zig");

    // Try to find a dependency file
    const deps_file = (try detector.findDepsFile(allocator, start_dir)) orelse {
        // No project found
        return .{ .exit_code = 1 };
    };
    defer allocator.free(deps_file.path);

    // Get the directory of the dependency file
    const project_dir = std.fs.path.dirname(deps_file.path) orelse start_dir;

    style.print("{s}\n", .{project_dir});

    return .{ .exit_code = 0 };
}

/// GitHub repo we ship releases from — must match `upgrade.zig`'s REPO so the
/// "update available" notice and `pantry upgrade` agree on the source.
const UPDATE_REPO = "pantry-pm/pantry";

/// Dev: check-updates command — detect a newer pantry release (best-effort,
/// silent). Fired backgrounded+disowned by the shell integration once per
/// session; the 24h throttle below means it only hits the network ~once/day.
///
/// Source is GitHub releases (same as `pantry upgrade`), NOT npm — they must
/// agree or the notice would advertise a version `upgrade` can't install.
///
/// Two files, deliberately separate:
///   ~/.pantry/.update-last-check   touched after every check → drives the 24h
///                                  throttle even when we're up to date (the old
///                                  code threw its throttle away on up-to-date
///                                  and re-hit the network every run).
///   ~/.pantry/.update-available    written (latest version) only when an update
///                                  exists; removed when up to date.
pub fn devCheckUpdatesCommand(allocator: std.mem.Allocator) !CommandResult {
    const version_options = @import("version");
    const current_version = version_options.version;

    const home = io_helper.getEnvVarOwned(allocator, "HOME") catch {
        return .{ .exit_code = 0 };
    };
    defer allocator.free(home);

    const pantry_dir = try std.fmt.allocPrint(allocator, "{s}/.pantry", .{home});
    defer allocator.free(pantry_dir);
    const marker_path = try std.fmt.allocPrint(allocator, "{s}/.update-available", .{pantry_dir});
    defer allocator.free(marker_path);
    const throttle_path = try std.fmt.allocPrint(allocator, "{s}/.update-last-check", .{pantry_dir});
    defer allocator.free(throttle_path);

    // Throttle: skip the network if we attempted a check within the last 24h.
    // Keyed on a dedicated stamp file so it holds regardless of outcome.
    if (io_helper.statFile(throttle_path)) |stat| {
        const now_sec: i128 = @intCast(io_helper.clockGettime().sec);
        const age_ns = now_sec * 1_000_000_000 - stat.mtime;
        if (age_ns < 86400 * 1_000_000_000) return .{ .exit_code = 0 };
    } else |_| {}

    // Stamp the attempt up-front: even if the network call below fails (offline),
    // we won't retry for 24h — otherwise an offline machine would hit GitHub on
    // every new shell.
    io_helper.makePath(pantry_dir) catch {};
    if (io_helper.createFile(throttle_path, .{ .truncate = true })) |f| {
        io_helper.closeFile(f);
    } else |_| {}

    // Ask GitHub for the latest release (same endpoint `upgrade` installs from).
    const api_url = "https://api.github.com/repos/" ++ UPDATE_REPO ++ "/releases/latest";
    const response = io_helper.httpGet(allocator, api_url) catch {
        return .{ .exit_code = 0 }; // network error — silent (background check)
    };
    defer allocator.free(response);

    const parsed = std.json.parseFromSlice(std.json.Value, allocator, response, .{}) catch {
        return .{ .exit_code = 0 };
    };
    defer parsed.deinit();

    if (parsed.value != .object) return .{ .exit_code = 0 };
    const tag_val = parsed.value.object.get("tag_name") orelse return .{ .exit_code = 0 };
    if (tag_val != .string) return .{ .exit_code = 0 };
    const tag = tag_val.string;
    const latest_version = if (tag.len > 0 and tag[0] == 'v') tag[1..] else tag;
    if (latest_version.len == 0) return .{ .exit_code = 0 };

    // Mirror `upgrade`'s own up-to-date test (string inequality of the tag) so
    // the notice and `pantry upgrade` never disagree.
    if (!std.mem.eql(u8, current_version, latest_version)) {
        const file = io_helper.createFile(marker_path, .{ .truncate = true }) catch {
            return .{ .exit_code = 0 };
        };
        defer io_helper.closeFile(file);
        io_helper.writeAllToFile(file, latest_version) catch {};
    } else {
        io_helper.deleteFile(marker_path) catch {};
    }

    return .{ .exit_code = 0 };
}
